# Generated by Django 4.0 on 2023-02-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkt', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
